name: Snapshot versions

on:
  issue_comment:
    types:
      - created

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  snapshot:
    name: Snapshots 📸
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - name: Deploy preview versions to NPM
        run: pnpm typescript:run ./.github/workflows/scripts/snapshot-versions.ts
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
